source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', require: 'sinatra/reloader'
gem 'slim'
gem 'rerun', github: 'alexch/rerun'
gem 'pg'
gem 'mysql2', '~> 0.5.2'
gem 'i18n'